name: test_server_deploy
on: workflow_dispatch 
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_TEST_SERVER_HOST }}
        username: ${{ secrets.SSH_TEST_SERVER_USER }}
        password: ${{ secrets.SSH_TEST_SERVER_PASSWORD }}
        port: 22
        source: "*.yml, *.json. *.png"
        target: "test"
        overwrite: true
