name: test_server_deploy
on: workflow_dispatch 
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy Data Folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_TEST_SERVER_HOST }}
        username: ${{ secrets.SSH_TEST_SERVER_USER }}
        password: ${{ secrets.SSH_TEST_SERVER_PASSWORD }}
        port: 22
        source: "data/resource_pack/*,data/resource_pack/assets/*/*,data/items_packs/*/*"
        target: "~/serverfiles/plugins/ItemsAdder/data"
        overwrite: true
        rm: true
    - name: Copy Lang Folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_TEST_SERVER_HOST }}
        username: ${{ secrets.SSH_TEST_SERVER_USER }}
        password: ${{ secrets.SSH_TEST_SERVER_PASSWORD }}
        port: 22
        source: "lang/*.yml"
        target: "~/serverfiles/plugins/ItemsAdder/lang"
        overwrite: true
        rm: true